version: "3.8"

services:
  delivery_data_db:
    container_name: delivery-percona-db
    platform: linux/x86_64
    image: percona:ps-5.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$ROOT_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DELIVERY_DATABASE
      - MYSQL_ROOT_HOST="%"
    ports:
      - $MYSQLDB_DELIVERY_LOCAL_PORT:$MYSQLDB_DELIVERY_DOCKER_PORT
    volumes:
      - type: bind
        source: $BASE_LOC/$DELIVERY_MYSQL_DATA_LOC
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: $BASE_LOC/$DELIVERY_INITIAL_SCRIPT_LOC
        target: /docker-entrypoint-initdb.d/1.sql
        volume:
          nocopy: true
  delivery_web_app:
      depends_on:
        - delivery_data_db
      container_name: delivery-web-app
      build:
        context: ./service/itlogiclab-restaurant-delivery
        dockerfile: Dockerfile
      restart: on-failure
      env_file: ./.env
      ports:
        - $DELIVERY_WEB_LOCAL_PORT:$DELIVERY_DOCKER_WEB_PORT
      environment:
        SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://delivery_data_db:$MYSQLDB_DELIVERY_DOCKER_PORT/$MYSQLDB_DELIVERY_DATABASE?useSSL=false",
              "spring.datasource.username" : "$DB_USER",
              "spring.datasource.password" : "$DB_PASSWORD",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "$DDL_OPTION",
              "spring.jpa.show-sql": "$SHOW_SQL"
            }'
      volumes:
        - type: bind
          source: $BASE_LOC/$DELIVERY_LOG_LOC
          target: /opt/multimoduleprojects/restaurant/logs
          volume:
            nocopy: true
      stdin_open: true
      tty: true