apiVersion: apps/v1
kind: Deployment
metadata: 
    name: billing-kube-deployment
    namespace: ckad-test
    labels: 
        app: billing-kube-app
        type: billing-kube-backend
        version: v1
spec: 
    selector: 
        matchLabels: 
            app: billing-app-kube-pod
    replicas: 1
    strategy:
                     type: RollingUpdate
    template: 
        metadata: 
           name: billing-kube-pod
           namespace: ckad-test
           labels: 
                app: billing-app-kube-pod
               # type: billing-app-kube-backend
        spec: 
           containers: 
                - name: billing-pod
                  image: pandeych009/itlogiclab-restaurant-billing-kube:1.0.1
                  imagePullPolicy: Always
                  resources: 
                      limits:
                          ##cpu: "1"
                          memory: "128Mi" 
                      requests:  
                          ##cpu: "1"
                          memory: "128Mi"          
                  ports:
                    - name: http 
                      containerPort: 20002
                      protocol: TCP
                  livenessProbe:
                      httpGet: 
                         path: /actuator/health
                         port: 20002
                      periodSeconds: 1800
                      initialDelaySeconds: 1800                                      
                  readinessProbe:
                      httpGet: 
                         path: /actuator/health
                         port: 20002
                      initialDelaySeconds: 4
                      periodSeconds: 4 
                  env: 
                    - name: MY_VALUE
                      value:  chandan
                        

---
apiVersion: v1
kind: Service
metadata: 
   name: billing-kube-service
   namespace: ckad-test
spec: 
   selector: 
       app: billing-app-kube-pod
   type: NodePort
   clusterIP: 10.101.102.102
   ports:
     - targetPort: 20002  ## PORT OF POD: PORT ON WHICH APP IS RUNNING
       port: 80  ## PORT OF SERVICE, DEFAULT 80. NEED TO CHECK HOW TO CHANGE IT.
       nodePort: 30002 # PORT WHERE AOO IS ACCESSIBLE:  Range: 30000 to 32767 